### ISSUE TITLE
Design Hero/Landing Page

### ISSUE THREAD

**Issue by NikhilSharma03** [NikhilSharma03/NFTCraft#3]
## Description

- Design Hero/Landing Page

**Comment by anshuman-dev** [comment]
We need to have:
1. Title 
2. An pallete menu just to the side of drawing space where user can find options of edit/erase/new colors/shapes.

**Comment by anshuman-dev** [comment]
@NikhilSharma03 Can you give me edit permissions for Figma file, it says View only.

**Comment by NikhilSharma03** [comment]
Got it @anshuman-dev. Just a sec

**Comment by NikhilSharma03** [comment]
@anshuman-dev I think there will be three pages

- Landing page - Regular landing page with details about project and button to navigate to Canvas and NFT collection page
- Canvas Page - Where you can draw and mint NFT
- NFT collections - where you can find all the created NFT's

**Comment by NikhilSharma03** [comment]
Closing this as we have decided on the UI.
